// Code generated by 'yaegi extract CliffCrack/engine/gfx'. DO NOT EDIT.

//go:build go1.25
// +build go1.25

package symbols

import (
	"CliffCrack/engine/gfx"
	"reflect"
)

func init() {
	Symbols["CliffCrack/engine/gfx/gfx"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"UIButton":    reflect.ValueOf(gfx.UIButton),
		"UICheckbox":  reflect.ValueOf(gfx.UICheckbox),
		"UIEnd":       reflect.ValueOf(gfx.UIEnd),
		"UISeparator": reflect.ValueOf(gfx.UISeparator),
		"UISlider":    reflect.ValueOf(gfx.UISlider),
		"UIText":      reflect.ValueOf(gfx.UIText),
		"UIWindow":    reflect.ValueOf(gfx.UIWindow),

		// type definitions
		"DrawCmd":     reflect.ValueOf((*gfx.DrawCmd)(nil)),
		"FrameParams": reflect.ValueOf((*gfx.FrameParams)(nil)),
		"Mesh":        reflect.ValueOf((*gfx.Mesh)(nil)),
		"Texture":     reflect.ValueOf((*gfx.Texture)(nil)),
		"UICmd":       reflect.ValueOf((*gfx.UICmd)(nil)),
		"UICmdKind":   reflect.ValueOf((*gfx.UICmdKind)(nil)),
		"UIInput":     reflect.ValueOf((*gfx.UIInput)(nil)),
		"UIOutput":    reflect.ValueOf((*gfx.UIOutput)(nil)),
	}
}
