// Code generated by 'yaegi extract CliffCrack/engine/mathx'. DO NOT EDIT.

//go:build go1.25
// +build go1.25

package symbols

import (
	"CliffCrack/engine/mathx"
	"reflect"
)

func init() {
	Symbols["CliffCrack/engine/mathx/mathx"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AxisAngle":    reflect.ValueOf(mathx.AxisAngle),
		"Decompose":    reflect.ValueOf(mathx.Decompose),
		"FromQuat":     reflect.ValueOf(mathx.FromQuat),
		"Hex":          reflect.ValueOf(mathx.Hex),
		"Identity":     reflect.ValueOf(mathx.Identity),
		"LookAt":       reflect.ValueOf(mathx.LookAt),
		"Nlerp":        reflect.ValueOf(mathx.Nlerp),
		"NormalMatrix": reflect.ValueOf(mathx.NormalMatrix),
		"Ortho":        reflect.ValueOf(mathx.Ortho),
		"Perspective":  reflect.ValueOf(mathx.Perspective),
		"QuatIdentity": reflect.ValueOf(mathx.QuatIdentity),
		"RotateX":      reflect.ValueOf(mathx.RotateX),
		"RotateY":      reflect.ValueOf(mathx.RotateY),
		"RotateZ":      reflect.ValueOf(mathx.RotateZ),
		"SRGB":         reflect.ValueOf(mathx.SRGB),
		"Scale":        reflect.ValueOf(mathx.Scale),
		"TransformDir": reflect.ValueOf(mathx.TransformDir),
		"Translate":    reflect.ValueOf(mathx.Translate),

		// type definitions
		"Mat4": reflect.ValueOf((*mathx.Mat4)(nil)),
		"Quat": reflect.ValueOf((*mathx.Quat)(nil)),
		"Vec3": reflect.ValueOf((*mathx.Vec3)(nil)),
	}
}
