// Code generated by 'yaegi extract vkgame/engine/gfx'. DO NOT EDIT.

//go:build go1.27
// +build go1.27

package symbols

import (
	"reflect"
	"vkgame/engine/gfx"
)

func init() {
	Symbols["vkgame/engine/gfx/gfx"] = map[string]reflect.Value{
		// type definitions
		"DrawCmd":     reflect.ValueOf((*gfx.DrawCmd)(nil)),
		"FrameParams": reflect.ValueOf((*gfx.FrameParams)(nil)),
		"Mesh":        reflect.ValueOf((*gfx.Mesh)(nil)),
		"Texture":     reflect.ValueOf((*gfx.Texture)(nil)),
	}
}
