// Code generated by 'yaegi extract vkgame/engine/scene'. DO NOT EDIT.

//go:build go1.27
// +build go1.27

package symbols

import (
	"reflect"
	"vkgame/engine/scene"
)

func init() {
	Symbols["vkgame/engine/scene/scene"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewTransform": reflect.ValueOf(scene.NewTransform),
		"NewWorld":     reflect.ValueOf(scene.NewWorld),

		// type definitions
		"Behaviour":  reflect.ValueOf((*scene.Behaviour)(nil)),
		"Entity":     reflect.ValueOf((*scene.Entity)(nil)),
		"ID":         reflect.ValueOf((*scene.ID)(nil)),
		"Renderable": reflect.ValueOf((*scene.Renderable)(nil)),
		"Transform":  reflect.ValueOf((*scene.Transform)(nil)),
		"World":      reflect.ValueOf((*scene.World)(nil)),
	}
}
